// verify-host.mjs -- acceptance check against the RUNNING dsh web host.
//
// ASCII only on purpose (PowerShell's Set-Content writes ANSI and node's fatal
// UTF-8 decode then fails). Do not edit this file with Set-Content.
//
// What it proves, in order:
//   1. the host's plugin compatibility gate accepts this package
//   2. the host serves this plugin's client bundle (from the live boot document)
//   3. the host answers this plugin's own RPC channel
//   4. folder rotation actually rotates: the wallpaper slot gains a DIFFERENT
//      image that really lives in the configured folder, and the wallpaper
//      route serves those exact bytes
//
// Step 4 performs one rotation, which is the feature under test. Everything
// else is read-only. For the offline logic self-check use `npm run selfcheck`.
//
// Usage: node verify-host.mjs [--url http://127.0.0.1:3080]

import { createHash, createHmac } from 'node:crypto'
import { existsSync, readFileSync, readdirSync, statSync } from 'node:fs'
import { homedir } from 'node:os'
import { join } from 'node:path'
import { pathToFileURL } from 'node:url'

const URL_FLAG = process.argv.indexOf('--url')
const BASE = URL_FLAG === -1 ? 'http://127.0.0.1:3080' : process.argv[URL_FLAG + 1]
const HOST = new URL(BASE).host
// Resolve the DSH home without baking any one machine's username into a public
// repository: honour DSH_HOME, else the OS home plus the conventional `.dsh`.
const DSH_HOME =
  process.env.DSH_HOME ?? join(homedir(), '.dsh')
const DATA_DIR = join(DSH_HOME, '.dsh-any-background-data')
const SLOT = join(DATA_DIR, 'wallpaper.jpg')
// Dual mode's second pane lives in its own slot file, beside the first.
const RIGHT_SLOT = join(DATA_DIR, 'wallpaper-right.jpg')
const CONFIG = join(DATA_DIR, 'theme-config.json')
const CREDENTIALS = join(DSH_HOME, '.credentials.yaml')

const sha = (b) => createHash('sha256').update(b).digest('hex')
const failures = []
function check(name, ok, detail = '') {
  console.log(`${ok ? 'PASS' : 'FAIL'} ${name}${detail === '' ? '' : ' - ' + detail}`)
  if (!ok) failures.push(name)
}

// --- Browser-session auth: the documented scheme behind the URL `dsh web` prints.
// The host signs a cookie with the secret it loaded for this profile, so this
// reproduces the browser's credential from the same credential store.
function authHeaders() {
  const b64u = (b) => Buffer.from(b).toString('base64').replaceAll('+', '-').replaceAll('/', '_').replace(/=+$/u, '')
  const creds = readFileSync(CREDENTIALS, 'utf8')
  const raw = /browser-session:[\s\S]*?secret:\s*(\S+)/u.exec(creds)
  if (raw === null) return undefined
  const secret = Buffer.from(raw[1].replaceAll('-', '+').replaceAll('_', '/'), 'base64')
  const name = 'dsh-auth-' + b64u(createHash('sha256').update(HOST).digest())
  const issuedAt = Date.now()
  const body = b64u(Buffer.from(JSON.stringify({ version: 1, authority: HOST, issuedAt, expiresAt: issuedAt + 3600_000 }), 'utf8'))
  return { cookie: `${name}=v1.${body}.${b64u(createHmac('sha256', secret).update(body).digest())}` }
}

const AUTH = authHeaders()
if (AUTH === undefined) {
  console.error(`cannot read the browser-session secret from ${CREDENTIALS}`)
  process.exit(2)
}

// --- 1. the host's compatibility gate, evaluated against the installed copy.
// Read the gate from the installed dsh rather than reimplementing semver: the
// real verdict is the whole point.
const installedDsh = (process.env.APPDATA ?? '') + '/npm/node_modules/@deepseek-ai/dsh/node_modules/@deepseek-ai'
const manifestPath = join(DSH_HOME, 'profiles', 'web', 'node_modules', 'dsh-any-background', 'package.json')
try {
  // Absolute Windows paths need a file:// URL in the ESM loader.
  const boot = await import(pathToFileURL(join(installedDsh, 'dsh-app-boot', 'lib', 'index.js')).href)
  const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'))
  const runtime = boot.getDshRuntimeVersion()
  const issue = boot.evaluatePluginCompatibility(manifest, {}, runtime)
  check('compat: the gate accepts this package on the running dsh', issue === undefined, issue === undefined ? `dsh ${runtime}` : JSON.stringify(issue).slice(0, 200))
} catch (error) {
  check('compat: the gate accepts this package on the running dsh', false, String(error?.message ?? error).slice(0, 200))
}

// --- 2. the live boot document advertises our client bundle.
const doc = await fetch(BASE + '/', { headers: AUTH })
const html = await doc.text()
check('bundle: the boot document lists our client half', html.includes('dsh-any-background/client.js'))
const combo = /"(plugins\/\?\?[^"]*dsh-any-background\/client\.js&rev=[0-9a-f]+)"/u.exec(html)
check('bundle: the boot document carries a rev for it', combo !== null)
if (combo !== null) {
  const res = await fetch(`${BASE}/${combo[1]}`, { headers: AUTH })
  const body = await res.text()
  check('bundle: the host serves the client bundle', res.status === 200, `HTTP ${res.status}, ${body.length} bytes`)
  check('bundle: the served bundle contains the folder UI', body.includes('dab-folder') && body.includes('rotSourceFolder'))
  check('bundle: the served bundle carries the adjustable cadence', body.includes('rotMinutes') && body.includes('rotEvery') && body.includes('intervalMinutes'))
}

// --- 3. the plugin's own RPC channel answers.
async function rpc(method, payload = {}) {
  const env = JSON.stringify({ type: 'client-request', rpcId: 'verify', method: `dshAnyBackground/${method}`, payload })
  const res = await fetch(`${BASE}/dsh-any-background/dshAnyBackground/${method}`, {
    method: 'POST',
    headers: { ...AUTH, 'content-type': 'application/json', 'content-length': String(Buffer.byteLength(env)) },
    body: env,
  })
  const parsed = JSON.parse(await res.text())
  return { status: res.status, result: parsed.result }
}

const read = await rpc('read')
check('rpc: read answers over the host transport', read.status === 200 && read.result?.ok === true, `HTTP ${read.status}`)
const cfg = read.result?.value?.config
if (cfg === undefined) {
  console.log('\nverify-host: cannot continue without a config response')
  process.exit(1)
}
const rot = cfg.rotation
console.log('config: ' + JSON.stringify({ source: rot.source, folder: rot.folder, folderCount: rot.folderCount, enabled: rot.enabled, mode: rot.mode, interval: rot.interval, intervalMinutes: rot.intervalMinutes }))
check('rpc: the host reports a native folder picker', read.result.value.folderPicker === true)
check('config: rotation is in folder mode', rot.source === 'folder' || rot.source === 'folders')
check('config: a folder is remembered', typeof rot.folder === 'string' && rot.folder.length > 0, String(rot.folder))

// --- 4. folder rotation really rotates.
if ((rot.source !== 'folder' && rot.source !== 'folders') || typeof rot.folder !== 'string') {
  console.log('\nverify-host: folder mode is not configured; skipping the rotation check')
  console.log(`verify-host: ${failures.length === 0 ? 'all checks passed' : failures.length + ' FAILED'}`)
  process.exit(failures.length === 0 ? 0 : 1)
}
// Dual mode writes a SECOND slot beside the left one, so every check that reads
// `SLOT` has to know whether it is looking at a half-painted pair. A stale host
// with no `dual` key answers `undefined`, which reads as "single lane".
const dual = rot.dual === true
// The third source: one directory per lane. It reports its right lane through
// `laneItems`, NOT through `dual` (the cadence and the mode are shared, the
// directories are not), so both lenses have to be consulted before deciding
// whether a right lane is expected.
const twoFolders = rot.source === 'folders'
const wantsRightLane = twoFolders || dual

// Index the folder by SIZE first: hashing all images would read gigabytes, and
// sizes alone narrow the slot's match to a handful of candidates.
const names = readdirSync(rot.folder).filter((n) => /\.(jpg|jpeg|png|gif|webp)$/iu.test(n))
const bySize = new Map()
for (const n of names) {
  const size = statSync(join(rot.folder, n)).size
  if (!bySize.has(size)) bySize.set(size, [])
  bySize.get(size).push(n)
}
function imageName(buf) {
  const hash = sha(buf)
  for (const n of bySize.get(buf.length) ?? []) {
    if (sha(readFileSync(join(rot.folder, n))) === hash) return n
  }
  return undefined
}
/** The same identity lookup, but rooted at an arbitrary directory: a two-folder
 *  rotation's right lane legitimately holds a file the LEFT folder has never
 *  seen, so its name can only be found in its own listing. */
function folderImageName(dir, buf) {
  const hash = sha(buf)
  for (const n of readdirSync(dir).filter((n) => /\.(jpg|jpeg|png|gif|webp)$/iu.test(n))) {
    if (sha(readFileSync(join(dir, n))) === hash) return n
  }
  return undefined
}
function slotName() {
  return imageName(readFileSync(SLOT))
}

const beforeHash = sha(readFileSync(SLOT))
const beforeName = slotName()
const advanced = await rpc('rotationAdvance')
check('rotate: rotationAdvance answers ok', advanced.result?.ok === true, JSON.stringify(advanced.result).slice(0, 160))

// Snapshot the slot for the ROUTE checks below. The `read` is placed straight
// after the advances, not between them: with a "reload" cadence every read
// advances too, so a read wedged between two advances adds a THIRD step and the
// slot can land back on the starting index by coincidence, which would look
// like a stuck rotation when the rotation is working exactly as designed.
await rpc('rotationAdvance')
await rpc('rotationAdvance')
const afterHash = sha(readFileSync(SLOT))
const afterName = slotName()
const after = (await rpc('read')).result.value.config.rotation
console.log('rotate: ' + JSON.stringify({ from: beforeName ?? '(not from the folder)', to: afterName ?? '(not from the folder)', index: after.current }))

// Guard first, assert second: with a single-image folder every advance lands
// back on the same file, and reporting that as a failure would blame the code
// for the fixture rather than the fixture for itself.
if (names.length <= 1) {
  console.log(`rotate: outcome check SKIPPED - the folder holds ${names.length} image(s), so every advance lands back on the same file`)
} else {
  check('rotate: the slot holds a different image', afterHash !== beforeHash)
}
check('rotate: the new image really lives in the configured folder', afterName !== undefined, String(afterName))
check('rotate: folderCount still counts every image', after.folderCount === names.length, `${after.folderCount} vs ${names.length}`)
check('rotate: folder mode survived the advance', after.source === rot.source && after.folder === rot.folder)
check('rotate: lastRotate was stamped', typeof after.lastRotate === 'string' && !Number.isNaN(Date.parse(after.lastRotate)))

// The browser loads the wallpaper from this route, so the served bytes are what
// the user actually sees.
const served = await fetch(BASE + '/dsh-any-background/wallpaper')
const servedBuf = Buffer.from(await served.arrayBuffer())
check('rotate: the wallpaper route answers 200', served.status === 200, `HTTP ${served.status}`)
check('rotate: the route serves the rotated bytes', sha(servedBuf) === afterHash)
check('rotate: what the route serves is that folder image', slotName() === afterName, String(afterName))

// Dual mode is the feature under test, so it gets its own read of the SECOND
// slot and of the record of which names each lane took. A single-lane wall must
// report no right lane at all - that is what tells the browser half to drop the
// second pane - and in folder mode the right lane is the next name after the
// left one, so the two must differ.
if (names.length > 1) {
  const rightBuf = existsSync(RIGHT_SLOT) ? readFileSync(RIGHT_SLOT) : null
  if (wantsRightLane) {
    check('dual: the right slot was written', rightBuf !== null, RIGHT_SLOT)
    if (rightBuf !== null) {
      // Two folders: the right lane walks its OWN directory, so its name must be
      // looked up there rather than in the left one - the picture is legitimately
      // absent from the left folder.
      const rightDir = twoFolders && typeof rot.folderRight === 'string' ? rot.folderRight : rot.folder
      const rightName = rightDir === rot.folder ? imageName(rightBuf) : folderImageName(rightDir, rightBuf)
      check('dual: the right slot holds a folder image', rightName !== undefined, String(rightName))
      // Same directory: the second lane is the next name, so the two must differ.
      // Two directories: they are independent listings, so a collision is legal
      // and the two may legitimately carry the same file name.
      if (!twoFolders) check('dual: the two lanes are different pictures', rightName !== afterName, `${afterName} vs ${rightName}`)
      check('dual: laneItems records both names', Array.isArray(after.laneItems) && after.laneItems.length === 2, JSON.stringify(after.laneItems))
    }
  } else {
    check('dual: a single-lane advance reports no right pane', (advanced.result?.wallpaperRightUrl ?? null) === null,
      `wallpaperRightUrl=${advanced.result?.wallpaperRightUrl}`)
    check('dual: a single-lane advance records one lane', Array.isArray(after.laneItems) && after.laneItems.length <= 1, JSON.stringify(after.laneItems))
  }
}

// A second advance proves the mode is not stuck on one image. Skipped when the
// cadence is `reload`: the `read` a few lines up already advanced, so with an
// odd folderCount landing on the same index the two advances cancel out and the
// check would fail on a rotation that is working exactly as designed. That is a
// property of the live cadence, not of the code under test.
if (rot.interval === 'reload') {
  console.log(`rotate: second-advance check SKIPPED - the live cadence is "${rot.interval}", whose own read already advances`)
} else {
  await rpc('rotationAdvance')
  check('rotate: a second advance moves on again', sha(readFileSync(SLOT)) !== afterHash, slotName() ?? '?')
}

// --- 5. the node half in memory is the one on disk.
// The client bundle is served from disk per request, so a rebuild always shows
// up there; the NODE half was imported when the host booted. Without a restart
// the running process keeps the old code, and the symptom is silent: a cadence
// the old normalizeRotation never heard of is quietly coerced to `daily`. Probe
// it by round trip, then put the live value back exactly as we found it — a
// verification run must not leave the machine in a different state.
{
  const before = (await rpc('read')).result.value.config
  const original = before.rotation.interval
  const originalMinutes = before.rotation.intervalMinutes
  // Probe with a gap that no earlier version could have stored, so a stale node
  // half fails the check rather than accidentally preserving the value.
  await rpc('writeConfig', { config: { ...before, rotation: { ...before.rotation, interval: 'minutes', intervalMinutes: 37 } } })
  const roundTripped = (await rpc('read')).result.value.config.rotation
  const live = roundTripped.interval === 'minutes' && roundTripped.intervalMinutes === 37
  check('node half: the running plugin knows the adjustable cadence', live,
    live ? 'minutes/37 round-tripped' : `coerced to "${roundTripped.interval}/${roundTripped.intervalMinutes}" - the host needs a restart to load the rebuilt node half`)
  // Restore unconditionally: on a live host this runs after the probe value was
  // accepted, which is exactly when it would otherwise be left behind.
  const back = (await rpc('read')).result.value.config
  if (back.rotation.interval !== original || back.rotation.intervalMinutes !== originalMinutes) {
    await rpc('writeConfig', { config: { ...back, rotation: { ...back.rotation, interval: original, intervalMinutes: originalMinutes } } })
  }
  const restoredCfg = (await rpc('read')).result.value.config.rotation
  const restored = restoredCfg.interval === original && restoredCfg.intervalMinutes === originalMinutes
  check('node half: the probe left the live config untouched', restored, `${restoredCfg.interval}/${restoredCfg.intervalMinutes} vs ${original}/${originalMinutes}`)
}

// --- 5b. dual mode survives the running node half.
// Same staleness trap as above: a host booted before this build has no `dual`
// in its normalizeRotation and silently drops the key, so the probe mirrors the
// block above and reports a stale process rather than a broken one. `dual` is a
// pure config flag - the lanes themselves need a picked folder, which this
// script cannot drive - so a round trip is what there is to check here. The
// right FOLDER's two keys ride along in the same probe: they are what makes the
// third source real, and an old normalizeRotation would drop them silently
// while the flag still came back, which is exactly the failure worth catching.
const liveRot = (await rpc('read')).result.value.config.rotation
const knowsDual = typeof liveRot.dual === 'boolean'
const knowsRightFolder = 'folderRight' in liveRot && 'folderRightCount' in liveRot
if (!knowsDual || !knowsRightFolder) {
  const missing = [!knowsDual && 'rotation.dual', !knowsRightFolder && 'rotation.folderRight'].filter(Boolean).join(', ')
  console.log(`dualLanes: SKIPPED - the running host predates this build (no ${missing}); restart the host to exercise it`)
  check('dualLanes: the running host is the current build', false,
    `the live config is missing ${missing} - the host booted before this build`)
} else {
  const before = (await rpc('read')).result.value.config
  check('dualLanes: the live config carries the flag', true, `dual=${before.rotation.dual}`)
  // The opposite of whatever is live, so a stale node half cannot preserve it
  // by accident, and the flag is restored afterwards. The right folder is
  // probed at the same time with a value that must survive verbatim.
  const probeRight = before.rotation.folderRight === null ? 'I:\\probe\\right' : null
  await rpc('writeConfig', { config: { ...before, rotation: { ...before.rotation, dual: !before.rotation.dual, folderRight: probeRight, folderRightCount: probeRight === null ? 0 : 7 } } })
  const back = (await rpc('read')).result.value.config.rotation
  check('dualLanes: the flag survives the round trip', back.dual === !before.rotation.dual, `dual=${back.dual}`)
  check('dualLanes: the lane list travels with it', Array.isArray(back.laneItems), `laneItems=${JSON.stringify(back.laneItems)}`)
  check('dualLanes: the right folder survives the round trip', back.folderRight === probeRight, `folderRight=${JSON.stringify(back.folderRight)}`)
  check('dualLanes: the right folder count survives the round trip', back.folderRightCount === (probeRight === null ? 0 : 7), `folderRightCount=${back.folderRightCount}`)
  await rpc('writeConfig', { config: { ...(await rpc('read')).result.value.config, rotation: { ...back, dual: before.rotation.dual, folderRight: before.rotation.folderRight, folderRightCount: before.rotation.folderRightCount } } })
  const restored = (await rpc('read')).result.value.config.rotation
  check('dualLanes: the probe left the live config untouched', restored.dual === before.rotation.dual && restored.folderRight === before.rotation.folderRight, `dual=${restored.dual} folderRight=${JSON.stringify(restored.folderRight)}`)
}

// --- 5c. the right lane's serve route is registered and refused safely.
// The route is what the browser half points the second pane at, so it has to
// exist even when nothing has been painted into its slot. A 404 is the correct
// "no picture stored" answer; anything 5xx is a broken handler.
{
  const before = (await rpc('read')).result.value.config.rotation
  const knowsRoute = typeof before.dual === 'boolean'
  if (!knowsRoute) {
    console.log('rightLane: SKIPPED - the running host predates this build; restart the host to exercise it')
    check('rightLane: the running host is the current build', false,
      'the live config has no rotation.dual key - the host booted before this build')
  } else {
    const res = await fetch(BASE + '/dsh-any-background/wallpaper-right')
    check('rightLane: the right serve route answers without a 5xx', res.status < 500, `status=${res.status}`)
    // An unsupported method must be refused explicitly rather than streamed.
    const post = await fetch(BASE + '/dsh-any-background/wallpaper-right', { method: 'POST' })
    check('rightLane: a POST is refused, not streamed', post.status === 405 || post.status === 401, `status=${post.status}`)
  }
}

console.log(`\nverify-host: ${failures.length === 0 ? 'all checks passed' : failures.length + ' FAILED'}`)
process.exit(failures.length === 0 ? 0 : 1)
